// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAFQBw86PGxrNw9_q0H3Awe8pvaggJm-4',
    appId: '1:203027922792:web:37af58355faa01f15ee0dd',
    messagingSenderId: '203027922792',
    projectId: 'early-detection-13473',
    authDomain: 'early-detection-13473.firebaseapp.com',
    storageBucket: 'early-detection-13473.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCONY9WBGo12msgaoSNXFv46ceKrMIyAhA',
    appId: '1:203027922792:android:16ecad75b9845ad35ee0dd',
    messagingSenderId: '203027922792',
    projectId: 'early-detection-13473',
    storageBucket: 'early-detection-13473.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDngyPhmBWdlfMajZddR8-RtG0_ySHyYU0',
    appId: '1:203027922792:ios:4274cd186f87ea175ee0dd',
    messagingSenderId: '203027922792',
    projectId: 'early-detection-13473',
    storageBucket: 'early-detection-13473.appspot.com',
    iosClientId: '203027922792-cnd9468h6n9uckp5nj7o08931laq17dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.earlyDetectionGraduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDngyPhmBWdlfMajZddR8-RtG0_ySHyYU0',
    appId: '1:203027922792:ios:4274cd186f87ea175ee0dd',
    messagingSenderId: '203027922792',
    projectId: 'early-detection-13473',
    storageBucket: 'early-detection-13473.appspot.com',
    iosClientId: '203027922792-cnd9468h6n9uckp5nj7o08931laq17dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.earlyDetectionGraduationProject',
  );
}
